# Generated by Django 4.2 on 2023-04-25 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='contacto_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente'),
        ),
    ]
